import { CreditCard, Eye, LockKeyhole, Plus, Settings2, ShieldCheck, Snowflake, Wifi } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/shared/page-header'
import { StatusBadge } from '../components/shared/status-badge'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card'
import { cn } from '../lib/utils'

export function CardsPage() {
  const [frozen, setFrozen] = useState(false)
  return <div className="space-y-6"><PageHeader eyebrow="Cards" title="Cards & controls" description="Manage your cards, spending controls, and security settings." actions={<Button><Plus className="size-4" />Add a card</Button>} />
    <section className="grid gap-6 xl:grid-cols-2">
      <div className="rounded-xl bg-primary p-6 text-primary-foreground shadow-sm sm:p-8"><div className="flex items-start justify-between"><span className="text-lg font-semibold tracking-tight">verdant</span><Wifi className="size-6 rotate-90 opacity-80" /></div><div className="mt-12 flex items-center gap-3"><span className="size-10 rounded-md bg-accent/80" /><span className="font-mono text-xl tracking-widest">•••• •••• •••• 4821</span></div><div className="mt-8 flex items-end justify-between"><div><p className="text-xs uppercase tracking-wider opacity-60">Cardholder</p><p className="mt-1 text-sm font-semibold">ANAND JOSEPH</p></div><div className="text-right"><p className="text-xs uppercase tracking-wider opacity-60">Expires</p><p className="mt-1 text-sm font-semibold tabular-nums">09/29</p></div><div className="flex -space-x-2"><span className="size-9 rounded-full bg-destructive/80" /><span className="size-9 rounded-full bg-warning/80" /></div></div></div>
      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Everyday debit</CardTitle><p className="mt-1 text-sm text-muted-foreground">Physical card · •••• 4821</p></div><StatusBadge status={frozen ? 'inactive' : 'active'}>{frozen ? 'frozen' : 'active'}</StatusBadge></CardHeader><CardContent className="space-y-3"><button onClick={() => setFrozen((value) => !value)} className={cn('flex w-full items-center gap-3 rounded-lg border border-border p-4 text-left hover:bg-muted', frozen && 'border-info bg-info')}><span className="flex size-10 items-center justify-center rounded-lg bg-secondary text-secondary-foreground">{frozen ? <LockKeyhole className="size-5" /> : <Snowflake className="size-5" />}</span><span className="flex-1"><span className="block text-sm font-semibold">{frozen ? 'Unfreeze card' : 'Freeze card'}</span><span className="block text-xs text-muted-foreground">{frozen ? 'Resume card activity' : 'Temporarily block transactions'}</span></span></button>{[{ icon: Eye, label: 'View card details', desc: 'Number, PIN, and CVV' }, { icon: Settings2, label: 'Spending controls', desc: 'Limits and merchant types' }, { icon: ShieldCheck, label: 'Security settings', desc: 'Alerts and verification' }].map(({ icon: Icon, label, desc }) => <button key={label} className="flex w-full items-center gap-3 rounded-lg border border-border p-4 text-left hover:bg-muted"><span className="flex size-10 items-center justify-center rounded-lg bg-muted text-muted-foreground"><Icon className="size-5" /></span><span><span className="block text-sm font-semibold">{label}</span><span className="block text-xs text-muted-foreground">{desc}</span></span></button>)}</CardContent></Card>
    </section>
    <section><h2 className="mb-4 text-lg font-semibold">Spending summary</h2><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent><CreditCard className="size-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">Spent this month</p><p className="mt-1 text-2xl font-semibold tabular-nums">$2,184.40</p></CardContent></Card><Card><CardContent><Settings2 className="size-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">Monthly limit</p><p className="mt-1 text-2xl font-semibold tabular-nums">$8,000.00</p></CardContent></Card><Card><CardContent><ShieldCheck className="size-5 text-credit" /><p className="mt-4 text-sm text-muted-foreground">Available to spend</p><p className="mt-1 text-2xl font-semibold tabular-nums">$5,815.60</p></CardContent></Card></div></section>
  </div>
}
