import { CalendarClock, Check, ChevronRight, Plus, ReceiptText, Send } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/shared/page-header'
import { StatusBadge } from '../components/shared/status-badge'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card'
import { Dialog } from '../components/ui/dialog'
import { Input } from '../components/ui/input'
import { Select } from '../components/ui/select'
import { paymentRecipients } from '../data/banking'

export function PaymentsPage() {
  const [open, setOpen] = useState(false)
  return <div className="space-y-6"><PageHeader eyebrow="Pay & transfer" title="Move money with confidence" description="Pay people and bills, or schedule a transfer in a few steps." actions={<Button onClick={() => setOpen(true)}><Send className="size-4" />New payment</Button>} />
    <section className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Send again</CardTitle><p className="mt-1 text-sm text-muted-foreground">Your recent recipients and billers</p></div><Button variant="ghost" size="sm"><Plus className="size-4" />Add</Button></CardHeader><CardContent className="space-y-2">{paymentRecipients.map((recipient) => <button key={recipient.name} onClick={() => setOpen(true)} className="flex w-full items-center gap-3 rounded-lg p-3 text-left hover:bg-muted"><span className="flex size-10 items-center justify-center rounded-full bg-secondary text-xs font-semibold text-secondary-foreground">{recipient.initials}</span><span className="flex-1"><span className="block text-sm font-semibold">{recipient.name}</span><span className="block text-xs text-muted-foreground">{recipient.detail}</span></span><ChevronRight className="size-4 text-muted-foreground" /></button>)}</CardContent></Card>
      <div className="space-y-4"><Card className="border-primary"><CardContent><span className="flex size-10 items-center justify-center rounded-lg bg-secondary text-primary"><CalendarClock className="size-5" /></span><p className="mt-5 text-sm text-muted-foreground">Upcoming payments</p><p className="mt-1 text-2xl font-semibold tabular-nums">$286.20</p><div className="mt-6 border-t border-border pt-4"><div className="flex justify-between text-sm"><span>Northstar Energy</span><span className="font-semibold">$146.20</span></div><div className="mt-3 flex justify-between text-sm"><span>Harbor Internet</span><span className="font-semibold">$140.00</span></div></div></CardContent></Card><Card><CardContent><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-success text-success-foreground"><Check className="size-5" /></span><div><p className="text-sm font-semibold">All bills are on track</p><p className="text-xs text-muted-foreground">No overdue payments</p></div></div></CardContent></Card></div>
    </section>
    <Card><CardHeader><CardTitle>Scheduled payments</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex items-center gap-4 rounded-lg border border-border p-4"><span className="flex size-10 items-center justify-center rounded-lg bg-warning text-warning-foreground"><ReceiptText className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Northstar Energy</p><p className="text-xs text-muted-foreground">Aug 2 · From Everyday checking</p></div><StatusBadge status="pending" /><span className="hidden text-sm font-semibold tabular-nums sm:block">$146.20</span></div><div className="flex items-center gap-4 rounded-lg border border-border p-4"><span className="flex size-10 items-center justify-center rounded-lg bg-info text-info-foreground"><ReceiptText className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Harbor Internet</p><p className="text-xs text-muted-foreground">Aug 4 · From Everyday checking</p></div><StatusBadge status="active">autopay</StatusBadge><span className="hidden text-sm font-semibold tabular-nums sm:block">$140.00</span></div></CardContent></Card>
    <Dialog open={open} onClose={() => setOpen(false)} title="New payment" description="Send a secure payment to a person or business."><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setOpen(false) }}><label className="grid gap-2 text-sm font-medium">Recipient<Input placeholder="Name, email, or account" required /></label><label className="grid gap-2 text-sm font-medium">From<Select><option>Everyday checking · $24,864.20</option><option>Growth savings · $42,120.84</option></Select></label><label className="grid gap-2 text-sm font-medium">Amount<Input type="number" min="1" placeholder="$0.00" required /></label><div className="flex justify-end gap-3 pt-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Review payment</Button></div></form></Dialog>
  </div>
}
